
spring:
  application:
    name: test-application
  config:
    import: optional:configserver:http://localhost:8888/

config-exchanger:
  aws-parameter-store:
    enabled: true

test:
  values:
    plain: "plain_value"
    secret: "secret_value"