name: CI Build

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make version
        run: |
          export version=v$(cat ./library/gradle.properties | grep version | awk -F "=" '{print $2}')
          git push --delete origin ${version} || true
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Tag version
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ env.VERSION }}