name: deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: source
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'gradle'

      - name: permit Gradle
        working-directory: ./source
        run: chmod +x gradlew

      - name: test
        working-directory: ./source
        run: ./gradlew :test-application:build test

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: source
          arguments: ":library:publish"

      # ============================================================================
      #                         Push published library files
      # ============================================================================
      - name: Checkout maven repo
        uses: actions/checkout@v3
        with:
          repository: iptv-devops/maven-repository
          path: repo
          token: ${{ secrets.MAVEN_REPO_DEPLOY_TOKEN }}
      - name: Publish library
        run: |
          cp -r ./source/library/build/publishing-repository/* ./repo
          cd repo
          git config user.email "iptv-devops@lguplus.co.kr"
          git config user.name "iptv-devops"
          git add .
          git commit -m "update"
          git push origin main
